apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  annotations:
    name: aws-observability
  labels:
    aws-observability: enabled

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
        Name              cloudwatch
        Match             *
        region            us-east-1
        log_group_name    /aws/eks/your-project/cluster
        log_stream_prefix nodes-
        auto_create_group true
  parsers.conf: |
    [PARSER]
        Name   json
        Format json


# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: aws-logging
#   namespace: aws-observability
# data:
#   flb_log_cw: "false" # Set to true to also ship Fluent Bit logs to CloudWatch
#   filters.conf: |
#     [FILTER]
#         Name parser
#         Match *
#         Key_name log
#         Parser crio
#     [FILTER]
#         Name
#  output.conf: |
#     [OUTPUT]
#       Name cloudwatch_logs
#       Match *
#       region us-east-1
#       log_group_name fluent-bit-cloudwatch
#       log_stream_prefix from-fluent-bit-
#       auto_create_group true
#       log_key log
