apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kube-system
  labels:
    app: kube-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-nginx
  template:
    metadata:
      labels:
        app: kube-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      tolerations:
            - key: "eks.amazonaws.com/compute-type"
              operator: "Equal"
              value: "fargate"
              effect: "NoSchedule"